package com.labmentix.speechmatrix.service.stt;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

/**
 * Mock STT provider â€” returns deterministic fake results.
 *
 * Activated by setting: app.stt.provider=mock
 *
 * Used for:
 *  - Unit and integration tests (no real HTTP calls)
 *  - Development without an API key
 *  - CI/CD pipelines
 *
 * The mock transcript is derived from the request so tests can
 * assert predictable output.
 */
@Component("mockSttProvider")
@Slf4j
public class MockSttProvider implements SttProvider {

    private static final String MOCK_TRANSCRIPT =
        "This is a mock transcription result generated by the test provider. " +
        "The Spring Boot Speech-to-Text application is working correctly. " +
        "Real transcription will be available when a valid API key is configured.";

    @Override
    public SttResult transcribe(SttRequest request) {
        log.debug("MockSttProvider.transcribe() called â€” returning fake result");
        return buildResult(request, MOCK_TRANSCRIPT);
    }

    @Override
    public SttResult transcribeBytes(byte[] audioBytes, SttRequest request) {
        log.debug("MockSttProvider.transcribeBytes() called â€” {} bytes", audioBytes.length);
        return buildResult(request, MOCK_TRANSCRIPT + " (from " + audioBytes.length + " bytes)");
    }

    @Override
    public PingResult ping() {
        log.debug("MockSttProvider.ping() called");
        return PingResult.ok("mock", "mock-v1", 1L);
    }

    @Override
    public String getProviderName() { return "Mock (test)"; }

    // â”€â”€ Helper â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    private SttResult buildResult(SttRequest request, String transcript) {
        // Simulate ~1s processing delay in dev â€” remove if too slow in tests
        // Uncomment for realistic feel: try { Thread.sleep(500); } catch (InterruptedException ignored) {}

        return SttResult.builder()
                .transcript(transcript)
                .confidence(0.99)
                .durationSeconds(estimateDuration(request))
                .detectedLanguage(request.getLanguage())
                .providerName(getProviderName())
                .build();
    }

    private double estimateDuration(SttRequest request) {
        if (request.getAudioBytes() != null) {
            // Rough estimate: 16kHz 16-bit mono = 32000 bytes/sec
            return request.getAudioBytes().length / 32_000.0;
        }
        if (request.getAudioFile() != null) {
            return request.getAudioFile().length() / 32_000.0;
        }
        return 5.0; // default for URL-based requests
    }
}
